# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xc16841A15d5F58a7ea9c3B781aC53A81963D1eE7"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0x3276456E6F7bc39637E2E674cc8DC96172E4e709
    decimals: 6
    name: USDT0
    standard: EvmHypSynthetic
    symbol: USDT0
  - addressOrDenom: "0x3276456E6F7bc39637E2E674cc8DC96172E4e709"
    chainName: polygon
    collateralAddressOrDenom: "0xc2132d05d31c914a87c6611c10748aeb04b58e8f"
    connections:
      - token: ethereum|blockx|0xc16841A15d5F58a7ea9c3B781aC53A81963D1eE7
    decimals: 6
    name: USDT0
    standard: EvmHypCollateral
    symbol: USDT0
