# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x72beb9E324C917Bd6A8e08BC9499894342DeeEfF"
    chainName: blockx
    connections:
      - token: ethereum|polygon|0xb5547dEaAB98923008d57843faEc805aDa24c307
    decimals: 18
    name: Test Token 2
    standard: EvmHypSynthetic
    symbol: TT2
  - addressOrDenom: "0xb5547dEaAB98923008d57843faEc805aDa24c307"
    chainName: polygon
    collateralAddressOrDenom: "0xa8E284C55140481c4c2803d90F345a6bDA00e705"
    connections:
      - token: ethereum|blockx|0x72beb9E324C917Bd6A8e08BC9499894342DeeEfF
    decimals: 18
    name: Test Token 2
    standard: EvmHypCollateral
    symbol: TT2
